In [1]:
import time
import re
import requests 
import numpy as np
import pandas as pd
import concurrent.futures

from bs4 import BeautifulSoup as bs
from fake_useragent import UserAgent
from tqdm import tqdm

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.common.exceptions import ElementNotInteractableException,NoSuchWindowException 

from selenium.webdriver.remote.remote_connection import LOGGER, logging
LOGGER.setLevel(logging.WARNING)

# Scraping prices of products off amazon

### Load excel from before

In [79]:
df = pd.read_excel('pricelist.xls')
df.head()

,Item,,Designer,Category,Item Name,Price,Qty Avail,Packaging,UPC/EAN,Case Count,Order Qty,Gender
0,12672,1.0,Abercrombie & Fitch,Regular,Abercrombie & Fitch Fierce 1.7 EDC Sp Men,46.5,56,New In Box,634349765,12,,Men
1,26413,1.0,Al Haramain,Regular,Al Haramain Amber Oud Tobacco Edition 2.0 EDP ...,38.5,more than 360,New In Box,6291100132171,- None -,,Men
2,10689,1.0,Alfred Sung,Regular,Alfred Sung Hei 3.4 EDT Sp Men,12.5,more than 360,New In Box,067724200017,24,,Men
3,13377,1.0,Alfred Sung,Regular,Alfred Sung Shi 3.4 EDP Sp Women,14.5,12,New In Box,067724271116,24,,Women
4,11668,1.0,Animale,Regular,Animale 3.4 EDP Sp Women,21.5,more than 360,New In Box,892456000037,24,,Women

In [80]:
df.columns

Index(['Item', ' ', 'Designer', 'Category', 'Item Name', 'Price', 'Qty Avail',
       'Packaging', 'UPC/EAN', 'Case Count', 'Order Qty', 'Gender'],
      dtype='object')

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1289 entries, 0 to 1288
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Item        1289 non-null   int64
 1               1284 non-null   float64
 2   Designer    1289 non-null   object
 3   Category    1289 non-null   object
 4   Item Name   1289 non-null   object
 5   Price       1289 non-null   float64
 6   Qty Avail   1289 non-null   object
 7   Packaging   1289 non-null   object
 8   UPC/EAN     1284 non-null   object
 9   Case Count  1289 non-null   object
 10  Order Qty   1289 non-null   object
 11  Gender      1289 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 121.0+ KB

In [82]:
# Make an array of the UPC values we will use to retrieve items.
upc_arr = df['UPC/EAN'].loc[df['UPC/EAN'] != '- None -'].to_numpy()
upc_arr

array(['634349765', '6291100132171', '067724200017', ..., '888874001541',
       '860002058931', '605930779929'], dtype=object)

In [83]:
# Helper function to search for product
def make_url(search_term):
    """
    Makes an amazon.ae search result url
    """
    return f'https://www.amazon.ae/s?k={search_term}'

### Try with one item

In [7]:
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("user-agent=[user-agent string]")
chrome_options.add_argument('--disable-notifications')
prefs = {"profile.default_content_setting_values.notifications" : 2}
chrome_options.add_experimental_option("prefs",prefs)
chrome_options.add_argument("window-size=1920,1080")

driver_manager = ChromeDriverManager().install()
driver = webdriver.Chrome(driver_manager,
                          options = chrome_options)


url = 'https://www.amazon.ae/s?k=3386460036757'
driver.get(url)
soup = bs(driver.page_source, 'html.parser') 

driver.quit()

====== WebDriver manager ======
Current google-chrome version is 97.0.4692
Get LATEST driver version for 97.0.4692
Get LATEST driver version for 97.0.4692
Trying to download new driver from https://chromedriver.storage.googleapis.com/97.0.4692.71/chromedriver_win32.zip
Driver has been saved in cache [C:\Users\Fardin\.wdm\drivers\chromedriver\win32\97.0.4692.71]

In [8]:
soup.find_all('span', {'class':'a-offscreen'})

[<span class="a-offscreen">AED 109.00</span>,
 <span class="a-offscreen">AED 184.38</span>,
 <span class="a-offscreen">AED 109.00</span>]

In [9]:
soup.find_all('span', {'class':'a-offscreen'})[0].text

'AED\xa0109.00'

In [10]:
def clean_price(price_text):
    """
    Cleans up the price text.
    """
    regex = r'[\d]+\.?[\d]+'
    
    return re.findall(regex,price_text)[0]

clean_price('AED\xa0184.38')

'184.38'

## Do with all items of interest

In [11]:
df

,Item,,Designer,Category,Item Name,Price,Qty Avail,Packaging,UPC/EAN,Case Count,Order Qty,Gender
0,12672,1.0,Abercrombie & Fitch,Regular,Abercrombie & Fitch Fierce 1.7 EDC Sp Men,46.5,56,New In Box,634349765,12,,Men
1,26413,1.0,Al Haramain,Regular,Al Haramain Amber Oud Tobacco Edition 2.0 EDP ...,38.5,more than 360,New In Box,6291100132171,- None -,,Men
2,10689,1.0,Alfred Sung,Regular,Alfred Sung Hei 3.4 EDT Sp Men,12.5,more than 360,New In Box,067724200017,24,,Men
3,13377,1.0,Alfred Sung,Regular,Alfred Sung Shi 3.4 EDP Sp Women,14.5,12,New In Box,067724271116,24,,Women
4,11668,1.0,Animale,Regular,Animale 3.4 EDP Sp Women,21.5,more than 360,New In Box,892456000037,24,,Women
...,...,...,...,...,...,...,...,...,...,...,...,...
1284,28529,NaN,Bond 9,HBA,Bond No. 9 Madison Square Park 6.4 Scented Candle,55.0,10,New In Box,888874002333,6,,Unisex
1285,28531,NaN,Bond 9,HBA,Bond No. 9 Nolita 6.4 Scented Candle,60.0,4,New In Box,888874005747,6,,Unisex
1286,28533,NaN,Bond 9,HBA,Bond No. 9 The Scent Of Peace 6.4 Scented Candle,55.0,6,New In Box,888874001541,2,,Unisex
1287,26724,NaN,Nuit D'Orient,HBA,Nuit D'Orient Hand Sanitizer 16.0 OZ. Pump,3.0,15,Unboxed,860002058931,24,,Unisex
1288,22811,NaN,THX,HBA,The Thx Co. Soap - Eucalyptus mint 5oz,2.0,151,New In Box,605930779929,50,,Unisex

In [12]:
df_reg = df.loc[df['Category'] == 'Regular']
df_reg.head()

,Item,,Designer,Category,Item Name,Price,Qty Avail,Packaging,UPC/EAN,Case Count,Order Qty,Gender
0,12672,1.0,Abercrombie & Fitch,Regular,Abercrombie & Fitch Fierce 1.7 EDC Sp Men,46.5,56,New In Box,634349765,12,,Men
1,26413,1.0,Al Haramain,Regular,Al Haramain Amber Oud Tobacco Edition 2.0 EDP ...,38.5,more than 360,New In Box,6291100132171,- None -,,Men
2,10689,1.0,Alfred Sung,Regular,Alfred Sung Hei 3.4 EDT Sp Men,12.5,more than 360,New In Box,067724200017,24,,Men
3,13377,1.0,Alfred Sung,Regular,Alfred Sung Shi 3.4 EDP Sp Women,14.5,12,New In Box,067724271116,24,,Women
4,11668,1.0,Animale,Regular,Animale 3.4 EDP Sp Women,21.5,more than 360,New In Box,892456000037,24,,Women

In [13]:
df_reg.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 781 entries, 0 to 780
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Item        781 non-null    int64
 1               781 non-null    float64
 2   Designer    781 non-null    object
 3   Category    781 non-null    object
 4   Item Name   781 non-null    object
 5   Price       781 non-null    float64
 6   Qty Avail   781 non-null    object
 7   Packaging   781 non-null    object
 8   UPC/EAN     781 non-null    object
 9   Case Count  781 non-null    object
 10  Order Qty   781 non-null    object
 11  Gender      781 non-null    object
dtypes: float64(2), int64(1), object(9)
memory usage: 79.3+ KB

In [14]:
upc_arr = df_reg['UPC/EAN'].loc[df_reg['UPC/EAN'] != '- None -'].to_numpy()
upc_arr.size

779

In [38]:
# Selenium settings
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("user-agent=[user-agent string]")
chrome_options.add_argument('--disable-notifications')
prefs = {"profile.default_content_setting_values.notifications" : 2}
chrome_options.add_experimental_option("prefs",prefs)
chrome_options.add_argument("window-size=1920,1080")

driver_manager = ChromeDriverManager().install()

pairs_list = []
for upc in tqdm(upc_arr):
    
    # New instance of driver.
    driver = webdriver.Chrome(driver_manager,
                          options = chrome_options)

    # Get ingo from page and close the page
    url = make_url(upc)
    driver.get(url)
    soup = bs(driver.page_source, 'html.parser') 
    driver.quit()
    
    # Parse page for required data
    soups_list = soup.find_all('span', {'class':'a-offscreen'})
    soup_texts = [item.text for item in soups_list]
    prices = [clean_price(price) for price in soup_texts]
    
    # Contextualize data
    tup_pair = (upc,prices)
    pairs_list.append(tup_pair)

====== WebDriver manager ======
Current google-chrome version is 97.0.4692
Get LATEST driver version for 97.0.4692
Driver [C:\Users\Fardin\.wdm\drivers\chromedriver\win32\97.0.4692.71\chromedriver.exe] found in cache
100%|██████████| 779/779 [1:34:53<00:00,  7.31s/it]

In [39]:
pairs_list

[('634349765', []),
 ('6291100132171', ['211.30']),
 ('067724200017', ['259.99']),
 ('067724271116', ['173.56']),
 ('892456000037', ['259.00', '454.16', '145.90']),
 ('892456000518', ['149.20']),
 ('892456000310',
  ['136.27', '212.06', '201.67', '189.19', '125.00', '345.16', '112.70']),
 ('892456000525', ['206.26']),
 ('8411061923221', ['58.21', '37.99', '43.65']),
 ('022548006719', ['232.03', '99.00', '111.65', '79.00']),
 ('812256020301',
  ['188.44',
   '186.00',
   '227.03',
   '57.00',
   '299.00',
   '78.00',
   '299.00',
   '99.00',
   '79.00',
   '235.00',
   '175.00',
   '299.00',
   '225.00',
   '79.00',
   '45.00']),
 ('812256022480', []),
 ('812256025467', []),
 ('812256021711', ['169.90']),
 ('812256024279',
  ['189.99',
   '201.15',
   '299.00',
   '299.00',
   '30.00',
   '79.00',
   '175.00',
   '299.00',
   '225.00',
   '225.00',
   '79.00',
   '135.00',
   '299.00']),
 ('3351500920037', ['167.58', '124.25', '108.37', '120.25']),
 ('3351500020409', ['124.25', '108.37']),
 ('3351500020416', ['220.50']),
 ('3351500012961', ['156.99']),
 ('3351500015245', ['94.00']),
 ('3351500005482', ['245.00']),
 ('3351500017997', ['95.00']),
 ('3351500016617', ['134.00']),
 ('3351500007783', ['170.99', '193.24']),
 ('3351500009848', ['134.21']),
 ('3351500012930', []),
 ('3351500013814', ['158.62']),
 ('3351500017485', ['200.45']),
 ('3351500017379', ['190.00']),
 ('715387003000', ['18.95', '144.54', '20.00']),
 ('3607340302565', ['48.00', '158.00']),
 ('3607344971385', ['63.70', '65.00', '132.00']),
 ('3607347575924', ['61.50']),
 ('0192139474606', []),
 ('0192139474842', []),
 ('888874002036', []),
 ('888874001466', ['415.84']),
 ('888874001992', ['574.00']),
 ('888874002609', ['625.78']),
 ('888874002418', ['103.00']),
 ('888874005631', ['685.00']),
 ('888874000964', ['563.27']),
 ('888874006829', ['258.69']),
 ('888874006065', []),
 ('888874002159', ['997.57']),
 ('888874005815', []),
 ('888874005853', ['889.66']),
 ('888874005723', ['860.99']),
 ('888874002128', ['995.00']),
 ('888874005648', ['983.98']),
 ('888874002777', ['578.67']),
 ('888874007123', []),
 ('888874001152', ['936.00']),
 ('888874001169', ['936.00']),
 ('3386460036757', ['109.00', '184.38', '109.00']),
 ('719346117722', ['167.00', '75.45', '156.00', '89.70', '111.91']),
 ('719346567442', ['74.00', '410.88', '70.10']),
 ('719346034425', ['81.48', '86.00', '98.98', '98.98', '98.98']),
 ('719346065405', ['64.40', '93.03']),
 ('719346191814', ['98.03']),
 ('719346246576', []),
 ('719346094665', ['99.23', '66.00']),
 ('719346249409', []),
 ('719346227537', ['95.00']),
 ('3614226905666', ['106.99', '189.90', '102.00']),
 ('3614226905376', ['120.00']),
 ('3614226904973', ['102.50', '106.49']),
 ('3614226905253', ['93.49']),
 ('3614226906410', []),
 ('3614226904966', ['111.54', '117.00']),
 ('3614226905185', ['106.75']),
 ('3616301838210', ['217.35']),
 ('3614227748767', ['84.34']),
 ('3614227748729', ['253.17']),
 ('3614226905284', ['92.00', '114.00']),
 ('783320402555', []),
 ('783320402722', ['279.62']),
 ('783320402739', ['192.68']),
 ('783320471506', ['583.17', '606.39']),
 ('783320971020', ['156.11', '379.00']),
 ('783320971525', ['179.00']),
 ('783320442001', []),
 ('783320402692', ['152.80']),
 ('783320402906', []),
 ('783320829413', ['188.95', '148.99']),
 ('7640111492955', ['69.00', '42.00']),
 ('7640111492108', ['57.75', '168.64', '171.11', '48.95']),
 ('3360373063680', ['159.00', '142.00']),
 ('3360374533205', ['158.99', '188.28', '145.00', '188.28', '128.20']),
 ('3360373048861', ['95.49', '102.64', '126.42', '128.20', '126.42']),
 ('3360373000074', ['101.49', '117.85', '117.85', '97.53']),
 ('3360373000081', ['164.15', '139.24', '164.15', '118.45']),
 ('088300104406', ['201.76', '70.00']),
 ('088300104437', ['89.00', '99.00', '74.39']),
 ('088300196890', ['63.70', '122.82', '53.95', '165.00', '349.00']),
 ('088300196814', ['360.56', '77.84', '75.00', '165.00']),
 ('088300196944', ['91.15', '84.00', '92.53']),
 ('3607343811835', ['64.35']),
 ('088300602513', ['90.36', '85.05']),
 ('088300000319', ['74.10']),
 ('3607342699465', []),
 ('088300608409', []),
 ('3614229135022', ['198.57']),
 ('3614229135145', ['195.52', '280.00']),
 ('088300101405', ['247.32', '180.00', '154.24', '90.00']),
 ('088300105519', ['87.00', '93.00']),
 ('3607341471727', ['105.26']),
 ('3614224821944', ['98.89']),
 ('3607342107977', ['69.00', '69.00']),
 ('3614225671371', ['213.09']),
 ('088300162543', ['146.00', '85.29', '280.00']),
 ('0088300162512', ['131.89', '144.04']),
 ('3607342686229', ['233.70']),
 ('088300193530', ['174.00', '103.99', '320.00']),
 ('031655644851', ['103.00', '338.13', '92.40', '250.00']),
 ('088300073627', ['116.99', '123.00', '243.78', '97.88']),
 ('3614226898494', ['276.63']),
 ('8411061896259', ['228.57', '138.50']),
 ('8411061865613', []),
 ('8411061865583', []),
 ('8411061711767', ['385.95', '203.00']),
 ('8411061723760', ['268.00', '187.95']),
 ('8411061782347', ['330.10', '299.77']),
 ('8411061870518', ['344.80']),
 ('8411061970935', ['218.99']),
 ('8411061838778', []),
 ('8411061970959', ['237.65']),
 ('8411061934234', ['210.50', '209.62', '179.50']),
 ('8411061926093', ['216.12']),
 ('8411061923245', ['439.00', '250.00']),
 ('8411061991909', []),
 ('8411061991886', []),
 ('8411061665039', ['379.99', '430.71']),
 ('8411061665022', ['370.00', '360.00', '497.41']),
 ('8411061607152', ['226.00', '267.00']),
 ('8411061962985', ['269.50']),
 ('8411061894842', ['178.99']),
 ('8411061894811', []),
 ('8411061071601', ['335.13', '350.06', '137.90', '147.99']),
 ('8411061823514', ['265.00']),
 ('8411061935965', ['126.93']),
 ('8411061819838', ['288.99']),
 ('8411061026250', ['288.99']),
 ('8411061818961', ['362.00']),
 ('8411061958483', ['006.54']),
 ('8411061944691', ['391.40']),
 ('8411061962015', []),
 ('8411061026298', []),
 ('8411061907559', ['326.47', '343.61']),
 ('8411061972168', ['284.22']),
 ('8411061972151', ['374.99', '400.00']),
 ('8411061081600', ['188.99', '220.50', '129.00']),
 ('8411061607275', ['423.70', '425.91']),
 ('8411061996973', []),
 ('3432240026767', ['434.46']),
 ('3432240026750', ['342.75', '299.00', '336.50']),
 ('3432240502193', ['564.90']),
 ('3432240502131', ['226.80', '490.00']),
 ('3432240501875', ['363.66']),
 ('3432240502100', ['606.87']),
 ('3432240504524', []),
 ('3432240504340', []),
 ('3432240031938', ['260.00']),
 ('3432240031921', ['269.00', '285.00', '319.99', '361.99']),
 ('3432240500373', ['186.99', '436.59']),
 ('3432240504319', []),
 ('3432240501363', []),
 ('3432240008459', ['777.00']),
 ('3432240005656', ['639.33']),
 ('3432240504203', []),
 ('3432240033741', ['222.00', '255.29']),
 ('3432240504807', []),
 ('3432240003638', ['201.60', '309.99', '241.74']),
 ('688575003659', ['74.92', '114.42']),
 ('5050456523757', ['83.25']),
 ('5050456523764', ['95.32']),
 ('3614222546047', []),
 ('3607347374305', ['264.86']),
 ('094922794536', ['128.00']),
 ('3348901181839', ['379.00', '485.00']),
 ('3348901206174', ['371.71', '504.00']),
 ('3348900236738', ['480.64']),
 ('3348900321861', ['349.23', '635.42', '385.00']),
 ('3348900103870', ['766.77']),
 ('3348900012189', ['273.00', '322.17', '512.66']),
 ('3348900012219', ['553.44', '329.00']),
 ('3348900147324', ['417.00']),
 ('3348901419147', ['326.47', '463.05']),
 ('3348900838178', ['287.99', '360.00']),
 ('3348900838185', ['459.00']),
 ('3348900425309', []),
 ('3348900417892', ['363.33', '485.07']),
 ('3348900417885', ['301.50', '392.74', '295.05']),
 ('3348901296632', ['339.72']),
 ('3348901521406', ['465.00']),
 ('3348901521512', ['542.38']),
 ('3348901263085', ['566.16']),
 ('3348901362856', ['391.74']),
 ('3348901362832', ['430.00']),
 ('3348901500821', []),
 ('3348901500838', ['851.42']),
 ('3348901561365', []),
 ('3348901368254', []),
 ('3348901250153', ['288.00', '288.00']),
 ('3348901486392', []),
 ('3348901368247', ['383.25']),
 ('3348901471534', ['545.74', '349.00']),
 ('3348901250146', ['478.00', '349.00']),
 ('3348901428545', ['614.99']),
 ('3348901321129', []),
 ('309979057993', ['64.86', '153.01']),
 ('309979047994',
  ['137.82',
   '137.00',
   '137.00',
   '93.50',
   '137.00',
   '153.35',
   '137.00',
   '137.00']),
 ('874034009366', []),
 ('020714694784', ['507.25']),
 ('020714080303', ['129.00', '306.51']),
 ('020714052959', ['143.19', '118.00', '129.47']),
 ('020714156893', ['264.00', '182.78', '179.00', '179.00']),
 ('020714881436', ['134.75', '210.09']),
 ('020714881429', ['168.00']),
 ('652638004037', ['785.36', '232.04', '815.00']),
 ('652638004013', ['413.20']),
 ('652638004631', ['969.00']),
 ('3386460109567', ['157.90']),
 ('3386460123501', []),
 ('3386460095341', ['202.00', '230.00']),
 ('3386460086332', ['124.03']),
 ('3386460078306', ['147.00']),
 ('3386460079136', ['137.67']),
 ('3386460086325', ['143.40']),
 ('3386460097659', []),
 ('3386460096867', []),
 ('3386460095464', ['205.07']),
 ('3508441104631', ['919.00']),
 ('3508441103665', []),
 ('3508440505118', ['698.25']),
 ('3508441104662', ['054.93']),
 ('3508441001114', ['199.00', '082.00']),
 ('3508441001268', ['707.00']),
 ('3508441001275', ['414.00', '965.66']),
 ('3508440505026', []),
 ('3508441001022', ['808.50', '333.00']),
 ('3508441001084', ['003.00']),
 ('3508441001039', []),
 ('3508441001046', ['430.78']),
 ('3508441001060', ['717.26']),
 ('3508440505057', ['893.03']),
 ('3508441001053', ['661.52', '865.00']),
 ('3508441104563', ['675.57']),
 ('3508441001169', ['830.00']),
 ('3508441001381', []),
 ('3508441001138', ['011.50']),
 ('3508440752055', []),
 ('3414202011820', ['42.00', '42.00']),
 ('3414202000510', ['64.95', '157.97']),
 ('3605522052826', ['158.32']),
 ('3614273356053', []),
 ('3605520946592', ['159.45', '201.99']),
 ('3605521034014', ['166.76', '235.08']),
 ('3605521806918', ['296.70']),
 ('4085400291001', ['54.00', '126.00']),
 ('4085400191509', ['99.00']),
 ('4085400272000', []),
 ('3423473020615', ['101.00', '105.84']),
 ('3423473020622', ['621.17']),
 ('3423473005353', ['161.60']),
 ('3423473101253', ['213.00']),
 ('3423473049456', ['174.30', '186.25']),
 ('3423473049654', ['308.18']),
 ('3423473020257', ['125.00']),
 ('3423473020523', []),
 ('3423473020264', ['191.00']),
 ('3423473020516', ['151.20', '168.65']),
 ('3423473020240', ['268.85', '285.29']),
 ('3423473032878', ['250.25']),
 ('3423222016036', []),
 ('3423222015961', []),
 ('3423222015978', []),
 ('3423473111559', ['122.25']),
 ('3423473109655', []),
 ('3423473109754', ['467.00']),
 ('3423473020639', ['167.28']),
 ('3423473020783', ['137.00']),
 ('3423473020776', ['178.00']),
 ('3423473020752', ['242.60']),
 ('3423473020998', ['154.80', '230.00']),
 ('3423473021230', ['121.50', '138.45']),
 ('3423473021001', ['214.49', '236.99']),
 ('3423473021360', ['221.99', '496.00']),
 ('3423473021209', ['166.00']),
 ('3423473021377', []),
 ('3423473021216', ['190.00']),
 ('3423222015763', []),
 ('3423478452657', ['196.35', '223.65']),
 ('022548121290', ['442.71', '772.37', '397.77']),
 ('763511100019', ['226.98']),
 ('763511101238',
  ['144.96',
   '184.99',
   '348.05',
   '151.52',
   '333.39',
   '183.57',
   '194.79',
   '468.66']),
 ('763511009824', ['195.00', '292.95', '322.19', '164.49']),
 ('022548172971', ['166.99', '454.16', '135.60']),
 ('022548237564', ['149.22', '285.18', '143.99', '185.00']),
 ('022548405772', []),
 ('022548386903', ['129.65']),
 ('8011003852741', ['154.41']),
 ('8011003852697', ['156.99']),
 ('094922912176', ['102.90', '340.63', '287.00', '287.00']),
 ('094922387066', ['142.22', '300.72', '481.41']),
 ('085805785345', ['61.52']),
 ('085805268848', ['100.00', '43.99']),
 ('085805004675', ['89.00', '82.80', '102.00']),
 ('085805558420', ['83.39']),
 ('085805120900', ['58.99', '66.75']),
 ('085805757748', ['61.19']),
 ('719346373906', ['64.00', '51.18']),
 ('719346013444', ['107.00', '144.00', '195.32']),
 ('719346010115', ['107.35']),
 ('719346125536', ['148.00', '162.00']),
 ('719346022705', ['106.98', '113.74', '81.00']),
 ('031655004419', ['82.00', '219.00']),
 ('5060455080168', ['123.93']),
 ('5060455080205', ['849.00']),
 ('3614229478693', ['441.56']),
 ('3614227594616', ['132.94']),
 ('8005610619323', ['140.46']),
 ('5060103310029', ['108.00', '289.90', '320.68']),
 ('027131086871', ['232.75', '242.99', '199.00']),
 ('027131006534', ['289.00', '240.00', '252.75']),
 ('027131004936', ['306.91', '183.69', '204.00', '199.00']),
 ('3355997000074', []),
 ('719346021814', ['57.41', '64.00']),
 ('719346021777', ['79.98', '209.00', '209.00']),
 ('3360372054559', ['299.00', '266.50', '315.78', '534.94']),
 ('3360372078500', ['458.22', '482.14', '453.00']),
 ('3614271992901', ['251.16']),
 ('3614271992932', ['379.49']),
 ('3614272865235', ['320.25', '436.00']),
 ('3614270157639', ['593.52', '334.87', '490.00', '273.00', '490.00']),
 ('3614270254697', ['336.00', '540.00']),
 ('3614272811935', []),
 ('3360372102359', ['325.16', '354.93']),
 ('3360372100515', ['225.88']),
 ('3614273195065', []),
 ('3360375006432', ['340.65', '398.42']),
 ('3614273195089', ['479.59']),
 ('3614272544420', []),
 ('3614272407442', []),
 ('3614272544024', ['537.47']),
 ('3614270426346', []),
 ('3605521965943', ['403.00']),
 ('3360372061830', ['279.00']),
 ('3605522041004', ['361.04']),
 ('3605522041486', []),
 ('3605522040281', []),
 ('3605522040588', ['232.00', '270.00']),
 ('3614272225718', ['277.00', '440.00']),
 ('3614272889491', ['247.80', '287.99']),
 ('3614272907690', ['320.00', '390.00']),
 ('3614272907904', []),
 ('3605521816658', ['314.00', '430.00']),
 ('3614273313162', ['603.62']),
 ('3614272889590', ['273.29']),
 ('716393009581', ['86.97', '223.61']),
 ('719346215183', ['128.50']),
 ('716393018859', ['92.76', '429.89', '394.21']),
 ('719346020190', ['117.00', '85.00', '187.69']),
 ('3610400000714', ['236.16', '79.33']),
 ('3274872396180', []),
 ('3274872274464', ['205.19']),
 ('3274870012143', ['190.00', '152.00']),
 ('3274879282363', ['188.99', '229.00', '269.00']),
 ('3274872394643', ['188.99']),
 ('3274872388239', ['192.00']),
 ('3607340426704', ['128.00', '243.67']),
 ('3614226761484', ['300.83', '515.00']),
 ('8005610367170', ['320.50']),
 ('3614227912076', ['221.62']),
 ('3616301976141', []),
 ('8005610328799', ['238.00']),
 ('3346470137059', ['259.58']),
 ('085715320919', ['56.99']),
 ('085715320117', ['56.71', '106.00']),
 ('085715320414', ['58.19', '58.19']),
 ('3360372017332', ['201.61', '201.61', '201.61', '149.00']),
 ('3346131610129', ['499.00']),
 ('3346131409914', ['339.13']),
 ('3346131402007', ['478.00', '389.75']),
 ('3346131403097', []),
 ('3346132100025', ['381.49', '298.65']),
 ('3614228830515', ['330.29', '415.00']),
 ('3614229828535', ['309.92', '411.00']),
 ('737052351100', ['125.00', '375.00']),
 ('3614228220897', []),
 ('3614228220880', ['400.66']),
 ('737052488257', ['136.70']),
 ('737052352060', []),
 ('737052766775', ['103.64', '375.00']),
 ('3616301623359', []),
 ('3614228220903', ['330.00']),
 ('737052933269', ['167.00', '480.00']),
 ('737052031415', ['360.56']),
 ('737052041353', []),
 ('737052232195', []),
 ('3614229823875', ['119.87']),
 ('737052849928', ['199.99']),
 ('3614229823790', ['73.21', '263.00']),
 ('3614229823806', ['109.85']),
 ('737052549972', ['39.96']),
 ('3616301623335', ['93.27']),
 ('3616301623298', []),
 ('8005610298924', ['206.99']),
 ('737052972305', []),
 ('3614228719056', ['401.98']),
 ('8005610298894', ['255.22', '415.00']),
 ('8005610689333', ['185.00']),
 ('3423222010324', ['399.02']),
 ('3423478516052', ['260.39']),
 ('3423470311358', ['174.30', '105.00', '280.01']),
 ('3423470485547', ['195.61', '158.85', '256.37']),
 ('3423470300154', ['132.90', '147.10', '199.99', '162.00']),
 ('3423470300161', ['188.31', '235.08', '173.82', '186.50', '186.50']),
 ('3423470311365',
  ['142.80', '189.00', '194.00', '235.08', '197.99', '414.18']),
 ('3423470485448', ['272.00', '470.55', '90.00', '191.10', '252.75']),
 ('3423478971752', ['181.91']),
 ('3355991002319', ['69.00']),
 ('3562700361005', ['102.00']),
 ('8435415011556', ['255.21', '265.00']),
 ('8435415017206', ['283.36']),
 ('8435415012638', ['265.00']),
 ('8435415012669', ['245.50']),
 ('8435415012690', ['309.00', '679.86', '685.33']),
 ('8435415018456', ['413.69']),
 ('8435415011990', ['352.58']),
 ('5050456110018', ['84.99']),
 ('608940535387', ['262.00', '117.75', '88.95']),
 ('608940540060', ['96.99', '128.14']),
 ('8431754342016', ['84.99', '377.00']),
 ('8431754006741', ['321.81']),
 ('8431754461519', ['494.33']),
 ('8431754007250', []),
 ('3386460097321', []),
 ('3386460103688', ['148.97']),
 ('3386460064132', ['197.82']),
 ('3386460082174', ['145.53', '136.00']),
 ('690251046768', []),
 ('690251046782', []),
 ('690251046737', []),
 ('690251088423', ['720.85']),
 ('690251088386', ['587.08']),
 ('3414206000608', ['62.00', '75.00']),
 ('098691036491', ['134.00', '134.65']),
 ('719346192118', ['94.50', '121.00']),
 ('719346232890', ['120.00']),
 ('098691047695', ['385.21']),
 ('098691047718', ['122.49', '157.70']),
 ('719346186568', ['214.02']),
 ('719346593946', ['167.78']),
 ('719346628372', ['226.98']),
 ('719346628365', ['120.00']),
 ('3770000002904', ['249.00']),
 ('3770000002775', ['338.50']),
 ('3770000002843', ['226.51']),
 ('3770000002805', ['449.50']),
 ('608940561737', ['229.06', '110.25']),
 ('608940553893', ['310.41', '113.35', '122.00']),
 ('608940580929', ['137.26']),
 ('608940573914', ['78.25']),
 ('608940556276', ['109.15', '107.35']),
 ('3352818717012', ['429.00', '349.00']),
 ('3274872390683', ['157.20', '166.90']),
 ('3700550218326', ['838.69']),
 ('737052413174', ['124.00', '350.00']),
 ('737052896045', ['204.60']),
 ('737052662664', ['123.90', '350.00']),
 ('8005610295312', ['153.94']),
 ('8005610295558', ['127.00', '355.00']),
 ('737052483214', ['145.74', '86.00', '340.00']),
 ('3614228836005', ['188.87']),
 ('737052191324', ['108.89', '108.25', '355.00']),
 ('3614273069175', ['314.70']),
 ('3614273203487', ['299.00', '327.49']),
 ('3605532612768', ['301.99']),
 ('3605533286555', ['404.99']),
 ('3614271579478', []),
 ('3614272026193', []),
 ('3147758029383',
  ['169.99', '184.94', '396.92', '245.00', '278.07', '332.00']),
 ('3147758034929', ['324.00', '319.85', '307.00', '117.63', '326.04']),
 ('3605532209067', ['220.15']),
 ('850009634061', []),
 ('850009634078', []),
 ('098691008719', ['92.61']),
 ('098691005046', ['107.23', '198.54']),
 ('719346134866', ['140.37']),
 ('098691035524', ['158.36']),
 ('719346180726', ['116.51']),
 ('719346504911', []),
 ('098691037603', ['93.25', '63.00']),
 ('098691046223', ['130.00', '88.72', '188.59']),
 ('098691046254', ['88.68', '164.88', '213.47']),
 ('098691026201', ['116.51', '205.45', '227.92']),
 ('098691026249', ['98.56', '223.93', '142.50', '220.35']),
 ('719346617307', ['112.02']),
 ('098691030475', ['88.72', '115.58']),
 ('098691030482', ['181.82', '223.93']),
 ('098691014918', ['331.54', '290.14', '207.77', '125.00']),
 ('098691018251', ['88.08']),
 ('098691018367', ['182.74', '88.08']),
 ('3760269848405', ['302.12']),
 ('3760269849549', []),
 ('3700559601396', ['530.00']),
 ('3760265190126', ['227.55']),
 ('3760265191734', ['295.07']),
 ('3760265190409', ['304.71']),
 ('3760265190485', []),
 ('3760265193257', ['267.91']),
 ('3760265190843', ['219.00']),
 ('3760265190966', ['199.00', '220.00']),
 ('3760265191048', ['246.00']),
 ('3760265192151', ['325.15']),
 ('0031655513027', ['301.04', '359.55']),
 ('031655513034', ['620.27', '620.27']),
 ('3607349764241', ['390.00', '255.00', '665.86', '250.00']),
 ('3614229159073', []),
 ('3607342221208', ['369.00', '371.00']),
 ('3614227372375', ['320.00']),
 ('719346121576', ['130.00', '232.68', '189.19', '90.99']),
 ('3595471061010', []),
 ('022548289655', ['555.39']),
 ('022548366448', []),
 ('022548397695', ['399.00']),
 ('8011003838493', ['198.00']),
 ('8011003832828', ['131.25']),
 ('3614225296802', ['185.75']),
 ('3386460101035', ['150.00', '350.00']),
 ('3386460121521', []),
 ('3386460121514', ['242.92']),
 ('3386460028424', ['81.00', '129.00']),
 ('3386460028394', ['98.00', '95.88', '137.34']),
 ('3386460032681', ['119.22', '310.00', '196.61']),

In [43]:
pairs_arr = np.array(pairs_list, dtype = object)
pairs_arr

array([['634349765', list([])],
       ['6291100132171', list(['211.30'])],
       ['067724200017', list(['259.99'])],
       ...,
       ['3365440002173', list(['285.00'])],
       ['3365440002197', list(['361.46', '349.00', '446.57'])],
       ['3614271716026', list(['240.00'])]], dtype=object)

In [45]:
with open('scraped.npy', 'wb') as f:
    np.save(f,pairs_arr)

### Continuing session later

In [16]:
pairs_arr = np.load('scraped.npy', allow_pickle = True)
pairs_arr

array([['634349765', list([])],
       ['6291100132171', list(['211.30'])],
       ['067724200017', list(['259.99'])],
       ...,
       ['3365440002173', list(['285.00'])],
       ['3365440002197', list(['361.46', '349.00', '446.57'])],
       ['3614271716026', list(['240.00'])]], dtype=object)

In [24]:
## Carrying off where We last left it
mask = df['Category'].isin(['Gift Set', 'Independent Brand', 'Body Product'])
df_g = df[mask]
df_g.head()

,Item,,Designer,Category,Item Name,Price,Qty Avail,Packaging,UPC/EAN,Case Count,Order Qty,Gender
781,26420,2.0,Ariana Grande,Gift Set,Ariana Grande Cloud 3.4 EDP 3PC Gift Set,48.0,more than 360,New In Box,812256027737,6,,Women
782,27479,2.0,Ariana Grande,Gift Set,Ariana Grande Thank U Next 3.4 EDP 3pc Women Set,44.0,146,New In Box,812256027720,6,,Women
783,28302,2.0,Armaf,Gift Set,Armaf Hunter Intense 4PC Men Set,23.5,2,New In Box,6294015136821,12,,Men
784,29311,2.0,Azzaro,Gift Set,Azzaro Chrome 3PC Men Set,41.0,145,New In Box,3351500017003,3,,Men
785,26811,2.0,Azzaro,Gift Set,Azzaro Wanted 3.4 EDT Sp + 3.4 Hair & Body Sha...,35.5,2,New In Box,3351500010813,3,,Men

In [25]:
df_g['Category'].unique()

array(['Gift Set', 'Independent Brand', 'Body Product'], dtype=object)

In [26]:
df_g.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 250 entries, 781 to 1216
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Item        250 non-null    int64
 1               250 non-null    float64
 2   Designer    250 non-null    object
 3   Category    250 non-null    object
 4   Item Name   250 non-null    object
 5   Price       250 non-null    float64
 6   Qty Avail   250 non-null    object
 7   Packaging   250 non-null    object
 8   UPC/EAN     250 non-null    object
 9   Case Count  250 non-null    object
 10  Order Qty   250 non-null    object
 11  Gender      250 non-null    object
dtypes: float64(2), int64(1), object(9)
memory usage: 25.4+ KB

In [28]:
upc_arrg = df_g['UPC/EAN'].loc[df_g['UPC/EAN'] != '- None -'].to_numpy()
upc_arrg.size

250

In [29]:
pairs_listg = []
for upc in tqdm(upc_arrg):
    
    # New instance of driver.
    driver = webdriver.Chrome(driver_manager,
                          options = chrome_options)

    # Get ingo from page and close the page
    url = make_url(upc)
    driver.get(url)
    soup = bs(driver.page_source, 'html.parser') 
    driver.quit()
    
    # Parse page for required data
    soups_list = soup.find_all('span', {'class':'a-offscreen'})
    soup_texts = [item.text for item in soups_list]
    prices = [clean_price(price) for price in soup_texts]
    
    # Contextualize data
    tup_pair = (upc,prices)
    pairs_listg.append(tup_pair)

100%|██████████| 250/250 [26:20<00:00,  6.32s/it]

In [33]:
# Save it too
with open('scraped2.npy', 'wb') as f:
    np.save(f,np.array(pairs_listg, dtype = object))

In [39]:
final_arr = np.vstack([pairs_arr,np.array(pairs_listg, dtype = object)])
final_arr

array([['634349765', list([])],
       ['6291100132171', list(['211.30'])],
       ['067724200017', list(['259.99'])],
       ...,
       ['0667548099257', list(['64.50'])],
       ['0667548099288', list(['42.94', '130.60'])],
       ['031655063102', list(['139.90'])]], dtype=object)

In [48]:
flist = final_arr.tolist()
flist[0:5]

[['634349765', []],
 ['6291100132171', ['211.30']],
 ['067724200017', ['259.99']],
 ['067724271116', ['173.56']],
 ['892456000037', ['259.00', '454.16', '145.90']]]

In [51]:
processed = []

for upc,prices in flist:
    if not prices:
        continue
    elif len(prices) == 1:
        processed.append((upc,float(prices[0])))
    else:
        processed.append((upc,float(min(prices))))
        
processed[0:5]

[('6291100132171', 211.3),
 ('067724200017', 259.99),
 ('067724271116', 173.56),
 ('892456000037', 145.9),
 ('892456000518', 149.2)]

In [76]:
idx = [x[0] for x in processed]
vals = [x[1] for x in processed]

col = pd.Series(vals, index = idx, name = 'scraped_price')
col = col*0.27
col

6291100132171    57.0510
067724200017     70.1973
067724271116     46.8612
892456000037     39.3930
892456000518     40.2840
                  ...
3607340373770    43.9506
3439600056259    89.1000
0667548099257    17.4150
0667548099288    35.2620
031655063102     37.7730
Name: scraped_price, Length: 773, dtype: float64

In [84]:
df = df.join(col, on = 'UPC/EAN')
df

,Item,,Designer,Category,Item Name,Price,Qty Avail,Packaging,UPC/EAN,Case Count,Order Qty,Gender,scraped_price
0,12672,1.0,Abercrombie & Fitch,Regular,Abercrombie & Fitch Fierce 1.7 EDC Sp Men,46.5,56,New In Box,634349765,12,,Men,NaN
1,26413,1.0,Al Haramain,Regular,Al Haramain Amber Oud Tobacco Edition 2.0 EDP ...,38.5,more than 360,New In Box,6291100132171,- None -,,Men,57.0510
2,10689,1.0,Alfred Sung,Regular,Alfred Sung Hei 3.4 EDT Sp Men,12.5,more than 360,New In Box,067724200017,24,,Men,70.1973
3,13377,1.0,Alfred Sung,Regular,Alfred Sung Shi 3.4 EDP Sp Women,14.5,12,New In Box,067724271116,24,,Women,46.8612
4,11668,1.0,Animale,Regular,Animale 3.4 EDP Sp Women,21.5,more than 360,New In Box,892456000037,24,,Women,39.3930
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1284,28529,NaN,Bond 9,HBA,Bond No. 9 Madison Square Park 6.4 Scented Candle,55.0,10,New In Box,888874002333,6,,Unisex,NaN
1285,28531,NaN,Bond 9,HBA,Bond No. 9 Nolita 6.4 Scented Candle,60.0,4,New In Box,888874005747,6,,Unisex,NaN
1286,28533,NaN,Bond 9,HBA,Bond No. 9 The Scent Of Peace 6.4 Scented Candle,55.0,6,New In Box,888874001541,2,,Unisex,NaN
1287,26724,NaN,Nuit D'Orient,HBA,Nuit D'Orient Hand Sanitizer 16.0 OZ. Pump,3.0,15,Unboxed,860002058931,24,,Unisex,NaN
1288,22811,NaN,THX,HBA,The Thx Co. Soap - Eucalyptus mint 5oz,2.0,151,New In Box,605930779929,50,,Unisex,NaN

In [85]:
df['price_difference'] = df['scraped_price']  - df['Price']
df.head()

,Item,,Designer,Category,Item Name,Price,Qty Avail,Packaging,UPC/EAN,Case Count,Order Qty,Gender,scraped_price,price_difference
0,12672,1.0,Abercrombie & Fitch,Regular,Abercrombie & Fitch Fierce 1.7 EDC Sp Men,46.5,56,New In Box,634349765,12,,Men,NaN,NaN
1,26413,1.0,Al Haramain,Regular,Al Haramain Amber Oud Tobacco Edition 2.0 EDP ...,38.5,more than 360,New In Box,6291100132171,- None -,,Men,57.0510,18.5510
2,10689,1.0,Alfred Sung,Regular,Alfred Sung Hei 3.4 EDT Sp Men,12.5,more than 360,New In Box,067724200017,24,,Men,70.1973,57.6973
3,13377,1.0,Alfred Sung,Regular,Alfred Sung Shi 3.4 EDP Sp Women,14.5,12,New In Box,067724271116,24,,Women,46.8612,32.3612
4,11668,1.0,Animale,Regular,Animale 3.4 EDP Sp Women,21.5,more than 360,New In Box,892456000037,24,,Women,39.3930,17.8930

In [102]:
conditions  = [np.isnan(df['price_difference']),\
              (df['price_difference'] > 0),\
              (df['price_difference'] <= 0)]
choices     = [np.nan, 'HIGHER', 'LOWER' ]
df['qualitative'] = np.select(conditions, choices)
    
df.head()

,Item,,Designer,Category,Item Name,Price,Qty Avail,Packaging,UPC/EAN,Case Count,Order Qty,Gender,scraped_price,price_difference,qualitative
0,12672,1.0,Abercrombie & Fitch,Regular,Abercrombie & Fitch Fierce 1.7 EDC Sp Men,46.5,56,New In Box,634349765,12,,Men,NaN,NaN,nan
1,26413,1.0,Al Haramain,Regular,Al Haramain Amber Oud Tobacco Edition 2.0 EDP ...,38.5,more than 360,New In Box,6291100132171,- None -,,Men,57.0510,18.5510,HIGHER
2,10689,1.0,Alfred Sung,Regular,Alfred Sung Hei 3.4 EDT Sp Men,12.5,more than 360,New In Box,067724200017,24,,Men,70.1973,57.6973,HIGHER
3,13377,1.0,Alfred Sung,Regular,Alfred Sung Shi 3.4 EDP Sp Women,14.5,12,New In Box,067724271116,24,,Women,46.8612,32.3612,HIGHER
4,11668,1.0,Animale,Regular,Animale 3.4 EDP Sp Women,21.5,more than 360,New In Box,892456000037,24,,Women,39.3930,17.8930,HIGHER

In [105]:
df['urls'] = df['UPC/EAN'].apply(lambda x: make_url(x))
df.head()

,Item,,Designer,Category,Item Name,Price,Qty Avail,Packaging,UPC/EAN,Case Count,Order Qty,Gender,scraped_price,price_difference,qualitative,urls
0,12672,1.0,Abercrombie & Fitch,Regular,Abercrombie & Fitch Fierce 1.7 EDC Sp Men,46.5,56,New In Box,634349765,12,,Men,NaN,NaN,nan,https://www.amazon.ae/s?k=634349765
1,26413,1.0,Al Haramain,Regular,Al Haramain Amber Oud Tobacco Edition 2.0 EDP ...,38.5,more than 360,New In Box,6291100132171,- None -,,Men,57.0510,18.5510,HIGHER,https://www.amazon.ae/s?k=6291100132171
2,10689,1.0,Alfred Sung,Regular,Alfred Sung Hei 3.4 EDT Sp Men,12.5,more than 360,New In Box,067724200017,24,,Men,70.1973,57.6973,HIGHER,https://www.amazon.ae/s?k=067724200017
3,13377,1.0,Alfred Sung,Regular,Alfred Sung Shi 3.4 EDP Sp Women,14.5,12,New In Box,067724271116,24,,Women,46.8612,32.3612,HIGHER,https://www.amazon.ae/s?k=067724271116
4,11668,1.0,Animale,Regular,Animale 3.4 EDP Sp Women,21.5,more than 360,New In Box,892456000037,24,,Women,39.3930,17.8930,HIGHER,https://www.amazon.ae/s?k=892456000037

In [106]:
df.to_excel('prices_joined.xlsx', index = False)

In [108]:
df_l = df.loc[df['qualitative'] == 'LOWER']
df_l.head()

,Item,,Designer,Category,Item Name,Price,Qty Avail,Packaging,UPC/EAN,Case Count,Order Qty,Gender,scraped_price,price_difference,qualitative,urls
14,26530,1.0,Ariana Grande,Regular,Ariana Grande Thank U Next 3.4 EDP Sp Women,36.5,3,New In Box,812256024279,24,,Women,36.4500,-0.0500,LOWER,https://www.amazon.ae/s?k=812256024279
38,23195,1.0,Bond 9,Regular,Bond No. 9 Bleecker Street 3.3 EDP Sp Unisex,220.0,49,New In Box,888874001466,3,,Unisex,112.2768,-107.7232,LOWER,https://www.amazon.ae/s?k=888874001466
41,23180,1.0,Bond 9,Regular,Bond No. 9 Central Park West 1.7 EDP Sp Unisex,100.0,22,New In Box,888874002418,3,,Unisex,27.8100,-72.1900,LOWER,https://www.amazon.ae/s?k=888874002418
42,27845,1.0,Bond 9,Regular,Bond No. 9 Dubai Black Sapphire 3.3 EDP Sp Unisex,205.0,1,New In Box,888874005631,3,,Unisex,184.9500,-20.0500,LOWER,https://www.amazon.ae/s?k=888874005631
44,26349,1.0,Bond 9,Regular,Bond No. 9 Gold Coast 3.4 EDP Sp Women,155.0,40,New In Box,888874006829,3,,Women,69.8463,-85.1537,LOWER,https://www.amazon.ae/s?k=888874006829

In [109]:
df_l.to_excel('lower.xlsx', index = False)